### ISSUE TITLE
Drop unknown keys from data when a custom function schema is provided

### ISSUE THREAD

**Issue by zoedsoupe** [zoedsoupe/peri#1]
Given that schema definition:

```elixir
defmodule MySchemas do
  import Peri

  defschema(:user, %{
    name: :string,
    age: :integer,
    email: {:required, :string}
  })

  defschema(:profile, %{
    user: {:custom, &user/1},
    bio: :string
  })
end
```

And this sample data:

```elixir
%{
  user: %{name: "John", age: 30, email: "john@example.com", extra_key: "value"},
  bio: "Developer",
  extra_key2: "value2"
}
```

The desired and expected output from `MySchemas.profile(data)` should be

```elixir
%{
  user: %{name: "John", age: 30, email: "john@example.com"},
  bio: "Developer"
}
```

Dropping any unknown key in nested schemas. The problem is that as the `user` schema
defined on the `profile` schema is an anonymous function, so, how we could get the actual inner schema for this capture?

`defschema/2` macro already creates a function called `get_schema/1` on the same module that defines the schema, it receives the name of the schema, as defined on the macro, and returns the actual schema.

That works for schemas like `{:custom, {mod, fun}}` or even `{:custom, {mod, fun, args}}`. But how about `{:custom, anonymous function}`? We need the module to invoke the `get_schema/1` function.

So i would like to hear ideas about this issue, that isn't a major problem in the library.

**Comment by HarisudhanRavi** [comment]
What if, instead of using `:custom` for nested schema, we can use `:schema`, a separate type to differentiate custom validations and nested schemas. It can also be handled differently inside. It will be like
```
defschema(:profile, %{
    user: {:schema, &user/1},
    bio: :string
  })
```
So that it will be useful when handling multiple custom validations and multiple nested schemas. I am not sure whether this gives any idea to your problem. Just my thought process :)

**Comment by zoedsoupe** [comment]
yeah, that's an interesting solution to explicit set nested schema definition, but the actual syntax for this can be achieved in 2 ways:

1. passing the schema validation function to as a custom type
```elixir
defmodule MySchemas do
  import Peri

  defschema :user, %{
    name: :string,
    age: :integer,
    email: {:required, :string}
  }

  defschema :profile, %{
    user: {:custom, &user/1},
    bio: :string
  }
end
```

2. define a single nested schema directly:
defmodule MySchemas do
  import Peri

  defschema :profile, %{
    user: %{
      name: :string,
      age: :integer,
      email: {:required, :string}
    },
    bio: :string
  }
end
```

The problem here is even we create a `{:schema, fun}` type, the schema would be also wrapped into an anonymous function so we could not know at runtime which schema name or structure is being defined, so we get the same problem.

the solution for now is to filter data before and after validating. what do you think?

**Comment by HarisudhanRavi** [comment]
I thought we can expect `{:schema, __MODULE__, func}`. But filter data is better than that.

Filtering out prior, rather than doing it in validation is a good idea.
I think you have already done it here https://github.com/zoedsoupe/peri/blob/9bb797ed5eb4e312531e082026f399c9d3d2e7e9/lib/peri.ex#L225
It is good to go.

**Comment by zoedsoupe** [comment]
currently we're filtering data and keys **after** the schema is validated, parsed and applied, so this solves this issue without any complexity, although could in some corner cases affect performance, but I think this is a fair trade-off.

```elixir
iex(13)> defmodule MySchemas do
...(13)>   import Peri
...(13)>
...(13)>   defschema(:user, %{
...(13)>     name: :string,
...(13)>     age: :integer,
...(13)>     email: {:required, :string}
...(13)>   })
...(13)>
...(13)>   defschema(:profile, %{
...(13)>     user: {:custom, &user/1},
...(13)>     bio: :string
...(13)>   })
...(13)> end
{:module, MySchemas,
 <<70, 79, 82, 49, 0, 0, 11, 196, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 62,
   0, 0, 0, 32, 16, 69, 108, 105, 120, 105, 114, 46, 77, 121, 83, 99, 104, 101,
   109, 97, 115, 8, 95, 95, 105, 110, 102, ...>>, {:profile!, 1}}
iex(14)> d = %{
...(14)>   user: %{name: "John", age: 30, email: "john@example.com", extra_key: "value"},
...(14)>   bio: "Developer",
...(14)>   extra_key2: "value2"
...(14)> }
%{
  bio: "Developer",
  extra_key2: "value2",
  user: %{age: 30, email: "john@example.com", extra_key: "value", name: "John"}
}
iex(15)> MySchemas.profile d
{:ok,
 %{bio: "Developer", user: %{age: 30, email: "john@example.com", name: "John"}}}
```
