### ISSUE TITLE
[FEATURE] Access to other fields during transform

### ISSUE THREAD

**Issue by nickdichev-firework** [zoedsoupe/peri#13]
**Description**
I need to access other fields in the schema when my transform function is running.

**Motivation**
This allows for more complex transforms. My use case is I need an extra field from the schema (in this case its an id) to pass to a context function which actually does the transform, the pattern is basically `fun(field_being_validated, other_field_in_schema)`.

**Alternatives**
I tried stringing together :dependent and :transform but it wasn't working quite right.

**Comment by zoedsoupe** [comment]
released [v0.2.12](https://hexdocs.pm/peri/0.2.12)!
