### ISSUE TITLE
Allow structs as data

### ISSUE THREAD

**Issue by dvv** [zoedsoupe/peri#6]
**Description**
Ability to validate potentially deeply nested structs is wanted

**Motivation**
Ability to validate data which does not implement `Access` protocol

**Alternatives**
`Peri.validate(schema, data |> Jason.encode!() |> Jason.decode!())` to switch to maps which do implement `Access` protocol

**Additional Context**
A dirty fix is to prepend https://github.com/zoedsoupe/peri/blob/main/lib/peri.ex#L335 with kinda:
```ex
  defp get_enumerable_value(struct, key) when is_struct(struct), do: get_enumerable_value(Map.from_struct(struct), key)
```
However, the authors may see another way.

TIA

**Comment by zoedsoupe** [comment]
Hello! Thank you for suggesting enhancements. Just for the sake my curiosity, could you provide some examples of usage of defining schemas and validations with structs?

I would like to think better on how to support them and if support them would break any of the features for now.

**Comment by dvv** [comment]
I'm exploring the following way of writing handlers:
```ex

defmodule ATypedFooResult do
  defstruct [x: MaybeAlsoAStruct]
end

post "/foo" do
  # validate input
  args = case Peri.validate(args_schema, conn.params) do
    {:ok, args} -> args
    {:error, errors} -> raise "Invalid arguments"
  end
  # do the stuff
  result = API.foo(args)
  # validate output (to conform API contract)
  result_schema = %{
    x: {:required, :map}, # TODO: replace `:map` with nested Peri schema
  }
  # NB: the following is not possible ATM
  %ATypedFooResult{x: %MaybeAlsoAStruct{y: %AsWellAsThisCanBeAStruct{}}} = result = case Peri.validate(result_schema, result) do
    {:ok, result} -> result
    {:error, errors} -> raise "Invalid result"
  end
  # respond with 200 result
  ...
end
```

**Comment by dvv** [comment]
Well, own structs may be made accessible via https://gist.github.com/andykingking/4982353b8c69ea301c698e97f6d34635

**Comment by zoedsoupe** [comment]
ok, addressing that!

**Comment by zoedsoupe** [comment]
fixed

**Comment by dvv** [comment]
Hi!
Am getting
```
(CaseClauseError) no case clause matching: {:error, [%Peri.Error{path:
[:email], key: :email, content: %{}, message: "is required", errors: nil}]}
    (peri 0.2.7) deps/peri/lib/peri.ex:264: Peri.validate/2
```
on the current master.
Please consider.
TIA

**Comment by zoedsoupe** [comment]
oh, i forget to handle nested schemas errors on raw data structures! just fixed
